// Animated demo GIFs for exercises, hot-linked from the FitSW exercise
// library CDN (fitsw.com/exercise-list). No public API or license exists
// for these assets — they can break or be blocked at any time.
const EXERCISE_GIFS: Record<string, string> = {
  "Ab Crunch Machine": "https://cdn.fitsw.com/assets/img/exerciseGifs/Machine_Abdominal_Crunch_Ab_Exercise_Demo_How-to.gif",
  "Arnold Press": "https://cdn.fitsw.com/assets/img/exerciseGifs/Arnold_Press_Shoulders_Delt_Exercise_Demo_How-to.gif",
  "Barbell Bent-Over Row": "https://cdn.fitsw.com/assets/img/exerciseGifs/Bent_Over_Barbell_Row_Exercise_Demo_How-to.gif",
  "Barbell Preacher Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Reverse_Barbell_Preacher_Curls_Biceps_Forearms_Arm_Exercise_Demo_How-to.gif",
  "Barbell Squat": "https://cdn.fitsw.com/assets/img/exerciseGifs/Barbell_Squat_Leg_Exercise_Demo_How-to.gif",
  "Battle Ropes": "https://cdn.fitsw.com/assets/img/exerciseGifs/Alternating-Vertical-Wave-Battle-Ropes.gif",
  "Bench Dips": "https://cdn.fitsw.com/assets/img/exerciseGifs/Tricep_Bench_Dips_Tricep_Exercise_Demo_How-to.gif",
  "Burpees": "https://cdn.fitsw.com/assets/img/exerciseGifs/Burpee_Exercise_Demo_How-to.gif",
  "Cable Crossover": "https://cdn.fitsw.com/assets/img/exerciseGifs/Cable_Crossover_Chest_Exercise_Demo_How-to.gif",
  "Cable Crunch": "https://cdn.fitsw.com/assets/img/exerciseGifs/Bosu_Ball_Cable_Crunch_with_Side_Bends_Abs_Core_Exercise_Demo_How-to.gif",
  "Cable Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/High-Cable-Curls.gif",
  "Cable Drag Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Bicep_Barbell_Drag_Curl_Exercise_Demo_How-to.gif",
  "Cable Face Pull": "https://cdn.fitsw.com/assets/img/exerciseGifs/Cable_Facepull_Exercise_Demo_How-to.gif",
  "Cable Pullover": "https://cdn.fitsw.com/assets/img/exerciseGifs/Rope_Straight_Arm_Pulldown_Back_Lat_Exercise_Demo_How-to.gif",
  "Cable Upright Row": "https://cdn.fitsw.com/assets/img/exerciseGifs/Cable_Upright_Row_Shoulders_-_Exercise_Demo.gif",
  "Calf Raise Machine": "https://cdn.fitsw.com/assets/img/exerciseGifs/Standing_Calf_Raises_Legs_Calf_Exercise_Demo_How-to.gif",
  "Close-Grip Bench Press": "https://cdn.fitsw.com/assets/img/exerciseGifs/Close-Grip_Barbell_Bench_Press_Chest_Pecs_Exercise_Demo_How-to.gif",
  "Concentration Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Dumbbell_Concentration_Curl_Exercise_Demo_How-to.gif",
  "Crunches": "https://cdn.fitsw.com/assets/img/exerciseGifs/Crunches_Exercise_Demo_How-to.gif",
  "Deadlift": "https://cdn.fitsw.com/assets/img/exerciseGifs/BandedHipHingeWithKettleBellDeadlift.gif",
  "Diamond Push-Ups": "https://cdn.fitsw.com/assets/img/exerciseGifs/How_To_Diamond_Push-Up.gif",
  "Dumbbell Lateral Raise": "https://cdn.fitsw.com/assets/img/exerciseGifs/Dumbbell_Lateral_Raise_Shoulder_Exercise_Demo_How-to.gif",
  "Dumbbell Pullover": "https://cdn.fitsw.com/assets/img/exerciseGifs/Dumbbell_Pullover_Exercise_Demo_How-to.gif",
  "Dumbbell Row": "https://cdn.fitsw.com/assets/img/exerciseGifs/Bent_Over_Two-Dumbbell_Row_Middle_Back_-_Exercise_Demo.gif",
  "Dumbbell Tricep Kickback": "https://cdn.fitsw.com/assets/img/exerciseGifs/Tricep_Kickbacks_Tricep_Exercise_Demo_How-to.gif",
  "EZ Bar Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Close-Grip_EZ_Bar_Curl_Biceps_Arm_Exercise_Demo_How-to.gif",
  "Flat Dumbbell Press": "https://cdn.fitsw.com/assets/img/exerciseGifs/Dumbbell_Bench_Press_Chest_Exercise_Demo_How-to.gif",
  "Forearm Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Palms-Up_Barbell_Wrist_Curl_Over_a_Bench_Wrists_Forearm_Grip-Strength_Exercise_Demo_How-to.gif",
  "Front Raise": "https://cdn.fitsw.com/assets/img/exerciseGifs/Alternating_Cable_Front_Raise_Shoulders_Delt_Exercise_Demo_How-to.gif",
  "Glute Bridge": "https://cdn.fitsw.com/assets/img/exerciseGifs/GluteBridge.gif",
  "Hack Squat": "https://cdn.fitsw.com/assets/img/exerciseGifs/Hack_Squat_Legs_Quad_Exercise_Demo_How-to_Quadriceps_Exercise.gif",
  "Hanging Leg Raise": "https://cdn.fitsw.com/assets/img/exerciseGifs/Hanging_Leg_Lift_Exercise_Demo_How-to.gif",
  "High Knees": "https://cdn.fitsw.com/assets/img/exerciseGifs/High_Knees_Cardio_Exercise_Demo_How-to.gif",
  "Hip Abductor/Adductor": "https://cdn.fitsw.com/assets/img/exerciseGifs/Thigh_Abductor_Legs_Abductor_Exercise_Demo_How-to.gif",
  "Incline Dumbbell Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Incline_Dumbbell_Curl_Biceps_Arm_Exercise_Demo_How-to.gif",
  "Incline Dumbbell Fly": "https://cdn.fitsw.com/assets/img/exerciseGifs/Incline_Dumbbell_Flyes_-_Pecs_Chest_Exercise_Demo_How-to.gif",
  "Incline Dumbbell Press": "https://cdn.fitsw.com/assets/img/exerciseGifs/Incline_Dumbbell_Press_Chest_Exercise_Demo_How-to.gif",
  "Jump Rope": "https://cdn.fitsw.com/assets/img/exerciseGifs/Jumping_Rope_Cardio_Exercise_Demo_How-to.gif",
  "Jump Squats": "https://cdn.fitsw.com/assets/img/exerciseGifs/Squat_Jumps.gif",
  "Jumping Jacks": "https://cdn.fitsw.com/assets/img/exerciseGifs/Jumping_Jacks_Cardio_Exercise_Demo_How-to.gif",
  "Lat Pulldown": "https://cdn.fitsw.com/assets/img/exerciseGifs/Cable_Kneeling_Lat_Pulldown_Lats_Back_-_Exercise_Demo.gif",
  "Leg Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Ankle_Weight_Leg_Curl_Legs_Hamstring_Exercise_Demo_How-to.gif",
  "Leg Extension": "https://cdn.fitsw.com/assets/img/exerciseGifs/Cable_Standing_Leg_Extension_Leg_Quad_Exercise_Demo_How-to.gif",
  "Leg Press": "https://cdn.fitsw.com/assets/img/exerciseGifs/Leg_Press_Legs_Quad_Exercise_Demo_How-to.gif",
  "Lunges": "https://cdn.fitsw.com/assets/img/exerciseGifs/Assisted_Reverse_Lunge_Exercise_Demo_How-to.gif",
  "Machine Preacher Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Preacher_Curls_Arms_Bicep_Exercise_Demo_How-to.gif",
  "Machine Row": "https://cdn.fitsw.com/assets/img/exerciseGifs/Machine_Row_Lats_Back_Exercise_Demo_How-to.gif",
  "Mountain Climbers": "https://cdn.fitsw.com/assets/img/exerciseGifs/Mountain_Climbers_Full_Body_Exercise_Demo_How-to.gif",
  "Oblique Cable Crunch": "https://cdn.fitsw.com/assets/img/exerciseGifs/Oblique_Cable_Crunch_Core_Ab_Exercise_Demo_How-to.gif",
  "One-Arm Cable Triceps Extension": "https://cdn.fitsw.com/assets/img/exerciseGifs/Cable_One_Arm_Tricep_Extension_Arms_Tricep_Exercise_Demo_How-to.gif",
  "One-Arm Standing Dumbbell Extension": "https://cdn.fitsw.com/assets/img/exerciseGifs/Single_Arm_Overhead_Extension_Dumbbell_Tricep_Exercise_Demo_How-to.gif",
  "Overhead Triceps Extension": "https://cdn.fitsw.com/assets/img/exerciseGifs/Cable_Rope_Overhead_Tricep_Extension_Exercise_Demo_How-to.gif",
  "Pec Deck Fly": "https://cdn.fitsw.com/assets/img/exerciseGifs/Pec_Fly_Machine_Chest_Pec_Exercise_Demo_How-to.gif",
  "Plank": "https://cdn.fitsw.com/assets/img/exerciseGifs/Bent_Knee_Side_Plank_Core_Exercise_Demo_How-to.gif",
  "Push-Ups": "https://cdn.fitsw.com/assets/img/exerciseGifs/Push-Ups_Chest_Exercise_Demo_How-to.gif",
  "Reverse Pec Fly": "https://cdn.fitsw.com/assets/img/exerciseGifs/Cable_Reverse_Fly_Shoulders_Upper_Back_Rear_Delt_Exercise_Demo_How-to.gif",
  "Roman Chair Twisting Knee Raise": "https://cdn.fitsw.com/assets/img/exerciseGifs/Hanging_Oblique_Knee_Raise_Abs_Core_Oblique_Exercise_Demo_How-to.gif",
  "Romanian Deadlift": "https://cdn.fitsw.com/assets/img/exerciseGifs/Barbell_Romanian_Deadlift_Legs_Hamstrings_Exercise_Demo_How-to.gif",
  "Russian Twist": "https://cdn.fitsw.com/assets/img/exerciseGifs/Russian_Twists_Exercise_Demo_How-to.gif",
  "Seated Cable Row": "https://cdn.fitsw.com/assets/img/exerciseGifs/Seated_Cable_Row_Exercise_Demo_How.gif",
  "Seated Dumbbell Triceps Extension": "https://cdn.fitsw.com/assets/img/exerciseGifs/Seated_Tricep_Overhead_Extension_Tricep_Exercise_Demo_How-to.gif",
  "Shoulder Press": "https://cdn.fitsw.com/assets/img/exerciseGifs/Bicep_Curl_to_Shoulder_Press_Biceps_Arms_Shoulder_Exercise_Demo_How-to.gif",
  "Skullcrusher": "https://cdn.fitsw.com/assets/img/exerciseGifs/Band_Skull_Crusher_Arms_Tricep_Exercise_Demo_How-to.gif",
  "Standing Barbell Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Barbell_Bicep_Curl_Straight_Bar_Arms_Bicep_Exercise_Demo_How-to.gif",
  "Standing Dumbbell Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Dumbbell_Bicep_Curl_Simultaneous_Exercise_Demo_How-to.gif",
  "Standing Hammer Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/Hammer_Curls_Arms_Bicep_Exercise_Demo_How-to.gif",
  "Standing High Pulley Cable Curl": "https://cdn.fitsw.com/assets/img/exerciseGifs/High-Cable-Curls.gif",
  "Sumo Dumbbell Squat": "https://cdn.fitsw.com/assets/img/exerciseGifs/Dumbbell_Squat_Quadriceps_-_Exercise_Demo.gif",
  "T-Bar Row": "https://cdn.fitsw.com/assets/img/exerciseGifs/T-bar_Row_Lats__Back_Exercise_Demo_How-to.gif",
  "Tricep Dip": "https://cdn.fitsw.com/assets/img/exerciseGifs/Dips_-_Triceps_Version_Triceps_Exercise_Demo_How-to.gif"
};

/** Animated demo GIF URL for an exercise, or null when FitSW has no
 *  equivalent (the app then shows only the video and photos). */
export function exerciseGif(name: string): string | null {
  return EXERCISE_GIFS[name] ?? null;
}
